# Grid parameters
grid_size: 10        # Grid size for RL
num_goal_cells: 3   # Num goals for RL
items_per_goal: 2    # Items per goal cell
obstacle_prob: 0.1

# RL parameters
carry_capacity: 1  # Max items robot can carry
gamma: 0.99        # Discount factor
theta: 0.001       # Convergence threshold
max_iters: 1000    # Maximum iterations for value iteration

# Visualization
visualize: true
render_fps: 2
step_delay: 1.0
max_steps: 100

# Other
random_seed: 0
num_starts: 4